# Generated by ChatGPT on 2025-02-14
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoundingFamilySignup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "child_age_range",
                    models.CharField(
                        choices=[
                            ("6-8", "6–8"),
                            ("9-11", "9–11"),
                            ("12-14", "12–14"),
                            ("15-16", "15–16"),
                        ],
                        max_length=8,
                    ),
                ),
                ("excited_for", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
