# Generated by Django 5.1.15 on 2026-02-18 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founding', '0002_update_age_bands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundingfamilysignup',
            name='child_age_range',
            field=models.CharField(choices=[('IMAGINAUTS', 'Imaginauts (6–10)'), ('NAVIGATORS', 'Navigators (11–13)'), ('TRAILBLAZERS', 'Trailblazers (14–16)')], max_length=50),
        ),
        migrations.CreateModel(
            name='FoundingFamilyChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(choices=[('IMAGINAUTS', 'Imaginauts (6–10)'), ('NAVIGATORS', 'Navigators (11–13)'), ('TRAILBLAZERS', 'Trailblazers (14–16)')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='founding.foundingfamilysignup')),
            ],
        ),
    ]
