# Generated by Django 5.1.15 on 2026-01-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='founding_member',
            field=models.BooleanField(default=False, help_text='Locked at £9.99/month forever'),
        ),
    ]
