# Generated by Django 5.1.15 on 2026-01-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscription_founding_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='avatar',
            field=models.CharField(choices=[('robot', '🤖 Robot'), ('rocket', '🚀 Rocket'), ('scientist', '🔬 Scientist'), ('astronaut', '👨\u200d🚀 Astronaut'), ('brain', '🧠 Brain'), ('star', '⭐ Star'), ('dino', '🦖 Dinosaur'), ('rainbow', '🌈 Rainbow'), ('planet', '🪐 Planet'), ('atom', '⚛️ Atom'), ('magnet', '🧲 Magnet'), ('telescope', '🔭 Telescope')], default='robot', max_length=20),
        ),
    ]
