# Generated by Django 5.1.15 on 2026-01-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_childprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='interests',
            field=models.JSONField(blank=True, default=list, help_text="List of child's interests from quiz"),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='learning_style',
            field=models.CharField(blank=True, help_text='Result from learning style quiz', max_length=50),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='quiz_completed',
            field=models.BooleanField(default=False),
        ),
    ]
