# Generated by Django 5.1.15 on 2026-01-26 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_childprofile_interests_childprofile_learning_style_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('science', 'Science'), ('tech', 'Technology'), ('engineering', 'Engineering'), ('art', 'Art'), ('math', 'Math')], max_length=20)),
                ('difficulty', models.IntegerField(default=1, help_text='1=Easy, 2=Medium, 3=Hard')),
                ('age_ranges', models.JSONField(default=list, help_text='List of age ranges: IMAGINAUTS, NAVIGATORS, TRAILBLAZERS')),
                ('tags', models.JSONField(default=list, help_text='Tags for recommendation matching')),
                ('emoji', models.CharField(default='🔬', max_length=10)),
                ('estimated_time', models.IntegerField(default=30, help_text='Estimated time in minutes')),
                ('materials_needed', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('rating', models.IntegerField(blank=True, help_text='1-5 stars', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text="Child's notes or reflections")),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_progress', to='users.childprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_progress', to='users.project')),
            ],
            options={
                'verbose_name': 'Project Progress',
                'verbose_name_plural': 'Project Progress',
                'ordering': ['-started_at'],
                'unique_together': {('child', 'project')},
            },
        ),
    ]
