# Generated by Django 5.1.15 on 2026-01-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_project_projectprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pdf_guide',
            field=models.FileField(blank=True, help_text='Printable PDF guide', null=True, upload_to='guides/'),
        ),
        migrations.AddField(
            model_name='project',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file (will be stored on Digital Ocean Spaces)', null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, help_text='Or paste YouTube/Vimeo URL'),
        ),
    ]
