# Generated by Django 5.1.15 on 2026-01-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_project_pdf_guide_project_video_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='avatar',
            field=models.CharField(choices=[('astronaut', '👨\u200d🚀 Astronaut'), ('scientist', '🔬 Scientist'), ('doctor', '👩\u200d⚕️ Doctor'), ('vet', '👨\u200d⚕️ Vet'), ('chef', '👨\u200d🍳 Chef'), ('artist', '👩\u200d🎨 Artist'), ('teacher', '👨\u200d🏫 Teacher'), ('firefighter', '👨\u200d🚒 Firefighter'), ('engineer', '👷 Engineer'), ('farmer', '👨\u200d🌾 Farmer'), ('mechanic', '👨\u200d🔧 Mechanic'), ('programmer', '👩\u200d💻 Programmer')], default='astronaut', max_length=20),
        ),
    ]
