# Generated by Django 5.1.15 on 2026-02-27 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_progression_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('emoji', models.CharField(default='⭐', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-is_featured', '-order_priority', '-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_published',
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Pin this to top of world'),
        ),
        migrations.AddField(
            model_name='project',
            name='minimum_stage',
            field=models.IntegerField(default=1, help_text='Child must be at this stage (1-5) to access'),
        ),
        migrations.AddField(
            model_name='project',
            name='order_priority',
            field=models.IntegerField(default=0, help_text='Higher numbers appear first within visibility category'),
        ),
        migrations.AddField(
            model_name='project',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Projects that must be completed first', related_name='unlocked_by', to='users.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Auto-publish at this date/time (leave blank for manual)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('spark', 'Spark (Quick 5-10 min touch)'), ('lab', 'Lab (Full project 30-60+ min)')], default='lab', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('hidden', 'Hidden'), ('scheduled', 'Scheduled (publish at date)'), ('live', 'Live'), ('coming_soon', 'Coming Soon (teaser)')], default='hidden', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(choices=[(1, '⭐ Minimal focus'), (2, '⭐⭐ Light focus'), (3, '⭐⭐⭐ Moderate focus'), (4, '⭐⭐⭐⭐ Heavy focus'), (5, '⭐⭐⭐⭐⭐ Primary focus')], default=3, help_text='How central is this skill to the project?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.skill')),
            ],
            options={
                'verbose_name': 'Project Skill',
                'verbose_name_plural': 'Project Skills',
                'unique_together': {('project', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='projects', through='users.ProjectSkill', to='users.skill'),
        ),
    ]
