# Generated by Django 5.1.15 on 2026-02-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_skill_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='badges_earned',
            field=models.JSONField(default=list, help_text='List of earned badge codes'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='creative_thinking',
            field=models.IntegerField(default=0, help_text='Growth in creative thinking pathway'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='current_stage',
            field=models.CharField(choices=[('EXPLORER', '🌱 Explorer'), ('EXPERIMENTER', '🔍 Experimenter'), ('BUILDER', '🧱 Builder'), ('DESIGNER', '🛠 Designer'), ('INDEPENDENT_MAKER', '🔥 Independent Maker')], default='EXPLORER', help_text='Current identity stage', max_length=30),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='practical_making',
            field=models.IntegerField(default=0, help_text='Growth in practical making pathway'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='problem_solving',
            field=models.IntegerField(default=0, help_text='Growth in problem solving pathway'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='resilience',
            field=models.IntegerField(default=0, help_text='Growth in resilience pathway'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='total_reflections',
            field=models.IntegerField(default=0, help_text='Count of thoughtful reflections'),
        ),
        migrations.AddField(
            model_name='project',
            name='skill_dimensions',
            field=models.JSONField(default=dict, help_text='Skill pathway boosts: {"creative_thinking": 3, "practical_making": 5, "problem_solving": 2, "resilience": 1}'),
        ),
    ]
