# Generated by Django 5.1.15 on 2026-02-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_childprofile_badges_earned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='instruction_steps',
            field=models.JSONField(blank=True, default=list, help_text='Optional structured steps. Example: [{"title": "Step 1", "description": "Do this", "image_url": "https://..."}]'),
        ),
    ]
