# Generated by Django 5.1.15 on 2026-02-28 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_project_instruction_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInstructionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='instruction_steps/')),
                ('image_alt_text', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction_step_items', to='users.project')),
            ],
            options={
                'verbose_name': 'Project Instruction Step',
                'verbose_name_plural': 'Project Instruction Steps',
                'ordering': ['order', 'id'],
            },
        ),
    ]
