# Generated by Django 5.1.15 on 2026-02-28 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_projectinstructionstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildHelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(blank=True, max_length=120)),
                ('problem', models.TextField()),
                ('tried_already', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='users.childprofile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_requests', to='users.project')),
            ],
            options={
                'verbose_name': 'Child Help Request',
                'verbose_name_plural': 'Child Help Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
