# Generated by Django 5.1.15 on 2026-02-28 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_childhelprequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='childhelprequest',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childhelprequest',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_request_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='childhelprequest',
            name='staff_reply',
            field=models.TextField(blank=True),
        ),
    ]
